insert into clientes(nombre,apellidos,sexo,telefono) values ('Manuel','Ubrique','M',154548155);
insert into clientes(nombre,apellidos,sexo,telefono) values ('Cristina','Llorens','F',6654428);
insert into clientes(nombre,apellidos,sexo,telefono) values ('Felipe','Contreras','M',65545554);
insert into clientes(nombre,apellidos,sexo,telefono) values ('Javier','Peña','M',666655541);
insert into clientes(nombre,apellidos,sexo,telefono) values ('Ernesto','Lorenzo','M',654789632);
insert into clientes(nombre,apellidos,sexo,telefono) values ('Gabriela','Garcia','F',66556544);
insert into clientes(nombre,apellidos,sexo,telefono) values ('Laura','Alvarez','F',656556522);
insert into clientes(nombre,apellidos,sexo,telefono) values ('Veronica','Poblada','F',65466452);
insert into clientes(nombre,apellidos,sexo,telefono) values ('Ignacio','Fernandez','M',65656454);
insert into clientes(nombre,apellidos,sexo,telefono) values ('Teodoro','Veroño','M',4565641225);
insert into clientes(nombre,apellidos,sexo,telefono) values ('Rafaela','Ruiz','F',64654811);
insert into clientes(nombre,apellidos,sexo,telefono) values ('Sonia','Orozko','F',65652232);
insert into clientes(nombre,apellidos,sexo,telefono) values ('Jacinta','Gutierrez','F',65621888);


insert into productos(nombre,descripcion,punitario,existencias) values ('fresas','1kg fresas',1.25,1000);
insert into productos(nombre,descripcion,punitario,existencias) values ('leche','1L leche semi',1.05,100);
insert into productos(nombre,descripcion,punitario,existencias) values ('platanos','1kg platano canarias',3.25,100);
insert into productos(nombre,descripcion,punitario,existencias) values ('peras','1kg peras conferencia',0.95,100);
insert into productos(nombre,descripcion,punitario,existencias) values ('batido','fresa',1.55,50);
insert into productos(nombre,descripcion,punitario,existencias) values ('pistachos','pistachos 250g',5.25,100);
insert into productos(nombre,descripcion,punitario,existencias) values ('servilleras','pack 100 servilletas',4.25,50);
insert into productos(nombre,descripcion,punitario,existencias) values ('gafas','gafas de sol',91.55,50);
insert into productos(nombre,descripcion,punitario,existencias) values ('radio','radio portatil',41.44,50);
insert into productos(nombre,descripcion,punitario,existencias) values ('fregona','fregona',0.34,10);
insert into productos(nombre,descripcion,punitario,existencias) values ('tila','',0.99,100);
insert into productos(nombre,descripcion,punitario,existencias) values ('tiritas','',1.99,100);
insert into productos(nombre,descripcion,punitario,existencias) values ('sabana','',3.98,10);
insert into productos(nombre,descripcion,punitario,existencias) values ('brocoli','',4.58,10);
insert into productos(nombre,descripcion,punitario,existencias) values ('pan molde','',3.66,10);
insert into productos(nombre,descripcion,punitario,existencias) values ('destornillador','',15.99,10);
insert into productos(nombre,descripcion,punitario,existencias) values ('mango','',10.25,50);
insert into productos(nombre,descripcion,punitario,existencias) values ('bastoncillos','',9.99,50);
insert into productos(nombre,descripcion,punitario,existencias) values ('paños','',5.55, 50);
insert into productos(nombre,descripcion,punitario,existencias) values ('carne','',18.66, 50);
insert into productos(nombre,descripcion,punitario,existencias) values ('cerezas','',6.25, 100);
insert into productos(nombre,descripcion,punitario,existencias) values ('mandarinas','',7.25, 100);

insert into ventas(folioAlbaran,id_cliente,id_producto,cantidad,subtotal,iva,total) values ('1',1,1,1,null,null,null);
insert into ventas(folioAlbaran,id_cliente,id_producto,cantidad,subtotal,iva,total) values ('1',1,2,1,null,null,null);
insert into ventas(folioAlbaran,id_cliente,id_producto,cantidad,subtotal,iva,total) values ('1',1,3,1,null,null,null);
insert into ventas(folioAlbaran,id_cliente,id_producto,cantidad,subtotal,iva,total) values ('2',2,4,1,null,null,null);
insert into ventas(folioAlbaran,id_cliente,id_producto,cantidad,subtotal,iva,total) values ('2',2,12,1,null,null,null);
insert into ventas(folioAlbaran,id_cliente,id_producto,cantidad,subtotal,iva,total) values ('3',3,6,1,null,null,null);
insert into ventas(folioAlbaran,id_cliente,id_producto,cantidad,subtotal,iva,total) values ('3',3,7,1,null,null,null);
insert into ventas(folioAlbaran,id_cliente,id_producto,cantidad,subtotal,iva,total) values ('3',3,9,1,null,null,null);
insert into ventas(folioAlbaran,id_cliente,id_producto,cantidad,subtotal,iva,total) values ('4',10,21,1,null,null,null);
insert into ventas(folioAlbaran,id_cliente,id_producto,cantidad,subtotal,iva,total) values ('4',10,11,1,null,null,null);
insert into ventas(folioAlbaran,id_cliente,id_producto,cantidad,subtotal,iva,total) values ('5',5,5,2,null,null,null);
insert into ventas(folioAlbaran,id_cliente,id_producto,cantidad,subtotal,iva,total) values ('5',5,6,1,null,null,null);
insert into ventas(folioAlbaran,id_cliente,id_producto,cantidad,subtotal,iva,total) values ('5',5,8,2,null,null,null);
insert into ventas(folioAlbaran,id_cliente,id_producto,cantidad,subtotal,iva,total) values ('5',5,13,1,null,null,null);
insert into ventas(folioAlbaran,id_cliente,id_producto,cantidad,subtotal,iva,total) values ('5',5,16,1,null,null,null);
insert into ventas(folioAlbaran,id_cliente,id_producto,cantidad,subtotal,iva,total) values ('6',6,1,1,null,null,null);
insert into ventas(folioAlbaran,id_cliente,id_producto,cantidad,subtotal,iva,total) values ('6',6,2,1,null,null,null);
insert into ventas(folioAlbaran,id_cliente,id_producto,cantidad,subtotal,iva,total) values ('6',6,3,1,null,null,null);
insert into ventas(folioAlbaran,id_cliente,id_producto,cantidad,subtotal,iva,total) values ('7',11,11,1,null,null,null);
insert into ventas(folioAlbaran,id_cliente,id_producto,cantidad,subtotal,iva,total) values ('7',11,12,1,null,null,null);
insert into ventas(folioAlbaran,id_cliente,id_producto,cantidad,subtotal,iva,total) values ('7',11,13,2,null,null,null);
